name: SmartInvs
version: 1.2.9
description: Inventory API for your Bukkit Plugins.
author: MinusKube
website: https://github.com/MinusKube/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin
api-version: 1.15